id: P005524
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:56:21.221434
source_metadata:
  id: bdr:W8LS17091
  title: སྐབས་གསུམ་པ།
  author: ''
  volumes:
    930ecb06f315497f9e933986f09ae28e:
      image_group_id: I8LS17099
      title: ''
      volume_number: 1
      total_pages: 504
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
