id: P005524
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS17091
  title: སྐབས་གསུམ་པ།
  author: ''
  volumes:
    930ecb06f315497f9e933986f09ae28e:
      image_group_id: I8LS17099
      title: ''
      volume_number: 1
      total_pages: 504
